name: Manually trigger an Azure Machine Learning job

on:
  workflow_dispatch:
  push:
    paths-ignore:
      - '.github/workflows/**'
    branches:
      - main

jobs:
  dev:
    environment: dev
    runs-on: ubuntu-latest
    steps:
    - name: Check out repo
      uses: actions/checkout@main
    - name: Install az ml extension
      run: az extension add -n ml -y
    - name: Azure login
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}
    - name: Trigger Job
      run: az ml job create --file src/job.yml --resource-group ${{secrets.AZURE_ML_RG}} --workspace-name ${{secrets.AZURE_ML_WORKSPACE}} --stream
  prod:
    needs: dev
    environment: prod
    runs-on: ubuntu-latest
    steps:
    - name: Check out repo
      uses: actions/checkout@main
    - name: Install az ml extension
      run: az extension add -n ml -y
    - name: Install dependencies
      run: |
        python -m pip install -r requirements.txt
    - name: Azure login
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}
    - name: Trigger Job
      run: az ml job create --file src/job-prod.yml --resource-group ${{secrets.AZURE_ML_RG}} --workspace-name ${{secrets.AZURE_ML_WORKSPACE}} --stream -o json > out.json

    - name: Parse and store runId
      id: extract_runid
      run: |
        runid_value=$(awk '/RunId:/ {print $2; exit}' out.json) 
        echo "::set-output name=runid_value::$runid_value"
    - name: Register and Deploy Model
      run: |
        echo "${{ steps.extract_runid.outputs.runid_value }}"
        python src/deploy.py --run-id=${{ steps.extract_runid.outputs.runid_value }}


